[tool:pytest]
addopts =
    --headed
    --browser chromium
    --base-url https://www.saucedemo.com
    --tracing on
    --screenshot only-on-failure
    --video retain-on-failure
    --html=test-results/report.html
    --alluredir=allure-results
    --self-contained-html

testpaths = tests

python_files = test_*.py *_tests.py
python_classes = Test*
python_functions = test_*

markers =
    playwright: marks tests as playwright tests